### ISSUE TITLE
Leave dump and pass in tact when modifying an entry

### ISSUE THREAD

**Issue by fgimian** [hercules-team/augeasproviders_mounttab#2]
Hello again, sorry for opening 2 issues in one day :smile: 

Suppose I start with this entry in fstab:

```
/dev/mapper/vg_volgrp01-lv_tmp /tmp                    ext4    defaults        1 2
```

And all I want to change is the options, I tried the following:

```
  mounttab { '/tmp':
    ensure   => present,
    options  => ['defaults', 'nodev', 'nosuid', 'noexec'],
    provider => augeas,
  }
```

However, this changes my pass and dump values too:

```
Notice: /Stage[main]/Profiles::Base::Compliance::Mounts/Mounttab[/tmp]/options: options changed 'defaults' to 'defaults,nodev,noexec,nosuid'
Notice: /Stage[main]/Profiles::Base::Compliance::Mounts/Mounttab[/tmp]/pass: pass changed '2' to '0'
Notice: /Stage[main]/Profiles::Base::Compliance::Mounts/Mounttab[/tmp]/dump: dump changed '1' to '0'
```

By comparison, my original augeas version didn't affect these parameters:

```
  augeas { 'set_tmp_mount_options':
    context => "/files/etc/fstab/*[file='/tmp']",
    changes => [
      "rm opt",
      "insert opt after vfstype",
      "set opt[last()] defaults",
      "insert opt after opt[last()]",
      "set opt[last()] nodev",
      "insert opt after opt[last()]",
      "set opt[last()] nosuid",
      "insert opt after opt[last()]",
      "set opt[last()] noexec",
    ],
  }
```

Granted it's rather ugly though, hehe :smile: 

Any help on this one would be awesome, and really sorry again for bothering you today

Cheers
Fotis

**Comment by fgimian** [comment]
I can see the original Puppet mounttab define does the same thing actually.  Is it a behaviour that you would reconsider in your module?

And forgive me for the really really silly question, but what exactly is the benifit of using this provider instead of the regular mounttab that comes with Puppet?

Thanks again
Fotis

**Comment by domcleal** [comment]
Yeah, I think I filed a bug report about it a very long time ago.  I'm not sure I'd be able to find it again, it's probably on the old Puppet Labs Redmine instance.

Unfortunately the mounttab module has just faded away - at one point it looked likely that the `mount` type in Puppet core would be replaced by mounttab+mountpoint, but nobody's worked on it for years so it seems unlikely now.

**Comment by fgimian** [comment]
That's such a shame really, especially for something so essential.  I might hunt around to see if anyone has implemented something that overcomes this but I imagine it is unlikely.  I'll report this against the official module repository and add a link here.

You're welcome to close this issue if you like though :smile: 

Thanks again for ally our help
Fotis

**Comment by domcleal** [comment]
Three years ago, how time flies: https://projects.puppetlabs.com/issues/16122.  It probably needs re-reporting into the MODULES project under JIRA.

Sorry there's no good solution, I hope it does get some life again.

**Comment by fgimian** [comment]
Wow, thanks for digging that up for me.  I guess I'm talking to the right person since you raised it (hehe).  I may try to re-file it in the new JIRA ticket tracker.

Cheers mate
Fotis
